// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAc2mWl5LhGPr5lYxovXG84VbV2ktBp4A',
    appId: '1:777835938091:web:765b0aa42fb323c2fe056e',
    messagingSenderId: '777835938091',
    projectId: 'ssdb-c6c69',
    authDomain: 'ssdb-c6c69.firebaseapp.com',
    storageBucket: 'ssdb-c6c69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_Ic0RNnO0tVLymSBR2ldP06CA1qqUvg',
    appId: '1:777835938091:android:781e7cc192d7344afe056e',
    messagingSenderId: '777835938091',
    projectId: 'ssdb-c6c69',
    storageBucket: 'ssdb-c6c69.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAc2mWl5LhGPr5lYxovXG84VbV2ktBp4A',
    appId: '1:777835938091:web:c124700bd25167b9fe056e',
    messagingSenderId: '777835938091',
    projectId: 'ssdb-c6c69',
    authDomain: 'ssdb-c6c69.firebaseapp.com',
    storageBucket: 'ssdb-c6c69.appspot.com',
  );

}